### ISSUE TITLE
Request for UE5 plugin

### ISSUE THREAD

**Issue by delebash** [PoseAI/PoseCameraAPI#1]
Could you produce a build version for UE5.  Thanks.

**Comment by PoseAI** [comment]
Hi we will try to look into this when feasible.  We haven't seen a lot of guidance for UE5 plugin development yet (as it is still in early access).  I would hope that the existing APIs still work and just dragging the PoseCamera folder into plugins of a UE5 project should compile.

**Comment by delebash** [comment]
Ok, I will test with UE4 to make sure everything works as expected then I will take a look at UE5 again and let you know.  Just dragging the PoseCamera folder into plugins for UE5 did not work as it said something like engine files where out of date.  However I created a blank C++ UE5 project and placed PoseCamera in the plugins folder and rebuilt.  Once this was done it loaded fine in a normal UE5 project.  The interface works in LiveLink and it shows connected.

**Comment by PoseAI** [comment]
I will mark this as closed as it seems you got it to work and we haven't heard back in awhile.
Yes you would need to rebuild the binaries for UE5 (dragging the folder and deleting the existing binaries/intermediate folders would probably also work), but it seems the existing C++ code is ok for the current state of UE5.
Thank you for testing it!
