### ISSUE TITLE
UnityDemo Cannot Pair Device Properly on Ubuntu 20.04

### ISSUE THREAD

**Issue by marcilzakour** [PoseAI/PoseCameraAPI#13]
- The python demo works fine and can receive the packets just fine.
- PoseAISourceDirect cannot pair UDP Clients.
- The code keeps waiting when it reaches [this line](https://github.com/PoseAI/PoseCameraAPI/blob/main/UnityAPI/UnityScripts/PoseAISourceDirect.cs#L127)
```c#
var waitany = WaitHandle.WaitAny(new[] { result.AsyncWaitHandle, _stopReceivingThread });
```
- Tried reconnecting multiple times with no success.

**Comment by PoseAI** [comment]
if you have a firewall active on Ubuntu try disabling/creating a rule as Unity often gets blocked by the firewall, and that is usually responsible for the vast majority of connection issues.

The Unity demo was developed for Windows (and also works on MacOS).  Can you try on Windows and see if you have an issue?  Networking code / socket access can sometimes be problematic on different platforms and I am not familiar with how Unity implements on Linux.

I will leave this open as we will try to take a look at supporting Unity in Linux at some point as well.

**Comment by marcilzakour** [comment]
After testing with Windows 10 environment, it turned out that it has the same issue. Python version work, while Unity does not.

**Comment by PoseAI** [comment]
In Windows, Can you please close Unity, try briefly disabling your firewall and Windows Defender and then relaunch Unity?  The behavior you describe really sounds like firewall is keeping Unity from receiving packets

**Comment by marcilzakour** [comment]
Thanks, it worked, I found the rule blocking the connection.

**Comment by PoseAI** [comment]
👍
