### ISSUE TITLE
There is a problem with the fingers in Unity

### ISSUE THREAD

**Issue by martint028** [PoseAI/PoseCameraAPI#14]
There is a problem with the fingers in Unity, the data of the thumb will be flipped from the iPhone or iPad, other fingers behave normally, and the whole body is normal
I have upgraded to the latest version

**Comment by PoseAI** [comment]
Hi, can you please tell us what rig you are using (i.e. Unity, Mixamo, Daz)?

**Comment by 3DNuzhyn** [comment]
Hello! Tell me how to use your program in UE5 with me model?

**Comment by PoseAI** [comment]
Closing issue due to lack of response
