### ISSUE TITLE
Hi, i have 2 questions

### ISSUE THREAD

**Issue by lucasjinreal** [PoseAI/PoseCameraAPI#15]
hi, does this:

1. unrealengine plugin can driven metahuman?
2. does it has python script sending detection result?

**Comment by PoseAI** [comment]
1. hi yes it can drive a metahuman.  We have a walkthrough in the info section of our website [www.poseai.co.uk](url).
2. we have a brief example python script here which shows how to stream JSON packets with all the animation data from the app to python.  This does not involve the unreal engine.  With the JSON you could read the data and connect with other applications
