### ISSUE TITLE
How to move in 3D?

### ISSUE THREAD

**Issue by SlimeVRX** [PoseAI/PoseCameraAPI#19]
Hi @PoseAI 

I recorded the data from python (socket) and then send data back to Unreal

I created an interface to be able to control Character.

![image](https://user-images.githubusercontent.com/99313947/197685651-9362ab94-0b55-4975-b3c1-a3c75c8761dc.png)

I noticed that quaternions only provide postural information. How to move characters in 3D?

Thank you very much!

Best regards,

Tin Nguyen Thanh

**Comment by SlimeVRX** [comment]
Hi @PoseAI 

I want to tell you about the research I'm working on. Research on posture estimation from 6 sensors.
After releasing the V1 version based on the TransPose article, now I have released the V2 version based on the PIP article, with many improvements, and smoother motion.

This is my latest test in Unity

Link 1: https://drive.google.com/file/d/1ZTnN37yazS60ipiwx6R2VwaiZ3wDMCw9/view
Link 2: https://drive.google.com/file/d/19UHiG1n5cqElEofuXWPYcXClD5GKmPqG/view

Data is processed in Python and then sent through Unity using Socket library
The position of 24 skeletons is transferred to the Unity-chan model

![image](https://user-images.githubusercontent.com/99313947/197782482-263aa950-5ed9-432d-8113-911ce3ee0c73.png)

Currently, I want to create a plug-in to send skeleton data from Python to Metahuman, Can you help me? I am familiar with Python language. I'm not familiar with Unreal, I started learning how to use Unreal. 

Please help me!

Best regards,

Tin Nguyen Thanh

**Comment by PoseAI** [comment]
Hi,
These all are questions for Epic Games and Unreal, not for us.  We are not related to Epic Games nor can we provide assistance on what looks to be your desire to create a plugin.  There are plenty of tutorials and information available in their documentation, examples in their codebase, and a discord channel where you can ask the Epic Community for help.  Good luck with your endeavors.

**Comment by SlimeVRX** [comment]
Hi! Thank you very much!
