### ISSUE TITLE
Webcam rather than Mobile?

### ISSUE THREAD

**Issue by matbeedotcom** [PoseAI/PoseCameraAPI#26]
Possible to use my PC webcam or a looping video file rather than Mobile for Live Pose?

**Comment by PoseAI** [comment]
Hi not currently (except on an apple silicon Mac you should be able to use webcam and run an ios app).  
We have not generally released the pc version of our engine to the public, only iOS for developers to test.  PC version is still corporate licensee only

We are planning on releasing a PC version in the next few months which can use webcam and videos however
