### ISSUE TITLE
pose data structure？

### ISSUE THREAD

**Issue by funnyQZQ** [PoseAI/PoseCameraAPI#4]
What a great work!

I want to predict human pose parameters with our own pose estimation model. However, i don't know how to transfer the 3D coordinates(x, y, z) to the quaternion.

Could you kindly help me out by providing some guidance? Thanks a lot!

**Comment by PoseAI** [comment]
Hello, 
3D joint data alone (from say a conventional pose estimation model) is insufficient to calculate the quaternions as rotations have additional degrees of freedom. For example you may have the elbow and wrist joint xyz position but still have infinite forearm rotations: to calculate the forearm rotation you would need additional information (for example roll around bone axis) to determine which way the forearm is facing. 

Our estimation models are designed to provide additional information which allows us to fully (and fairly accurately) estimate the quaternions.
