### ISSUE TITLE
Finger tracking issues with PoseAI and Action Figures

### ISSUE THREAD

**Issue by HeadClot** [PoseAI/PoseCameraAPI#8]
Hey - I am having an issues with finger tracking. To give some context I am using an [Drawing Reference Action figure](https://www.amazon.com/Drawing-Action-Figures-Female-Artists/dp/B09NKRJGJX/) from Amazon. You can see the results below. As you can see the fists are not clenched but are straight. Is there any way to correct this? 

![image](https://user-images.githubusercontent.com/1534098/154582087-58efa10b-9ef2-467e-80b6-3b946bd4bfcd.png)
![image](https://user-images.githubusercontent.com/1534098/154582165-eb36ad79-6c49-4a07-acb0-5ac116d7bc4f.png)

**Comment by PoseAI** [comment]
Hi, so are you aiming the iPhone camera at a picture (ie the anime cartoon you posted)?  1. The hands need a very good resolution base image: ideally just the hands should be fill around 200 pixels square.  So if using non live stream make sure resolution is high.
2. The AI is trained mostly on ungloved hands as our assumption is a user filming themselves is not wearing gloves inside.
3. A cartoon hand is not the same as a human hand so accuracy may suffer versus real images.

and just to confirm, you are using a mode with hands (not say RoomBodyOnly)

**Comment by PoseAI** [comment]
Hi, I see you were actually using a small figure as your reference model.  That is not really an optimal subject - you will do better using photos of posed models if you want to use reference material.  As we haven't heard anything back we will close the issue.  Cheers
